# Generated by Django 4.2.1 on 2023-06-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('DOB', models.CharField(max_length=500)),
                ('PHONE', models.CharField(max_length=20)),
                ('DESCRIPTION', models.CharField(max_length=500)),
            ],
        ),
    ]
