# Generated by Django 4.2.1 on 2023-06-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('DEPERTMENT', models.CharField(max_length=500)),
                ('DEGREE', models.CharField(max_length=500)),
                ('RESULT', models.CharField(max_length=20)),
                ('INSTETUDE', models.CharField(max_length=500)),
                ('STATUS', models.CharField(max_length=500)),
            ],
        ),
    ]
